### ISSUE TITLE
This arm64 binary already contains an `LC_BUILD_VERSION` load command

### ISSUE THREAD

**Issue by markst** [darrarski/xcframework-maker#5]
Using `make-xcframework` works great from my fat framework without the `-arm64sim` flag. 

However I'm unable to generate with the `-arm64sim` flag. 
The following output occurs:
```
Error: This arm64 binary already contains an LC_BUILD_VERSION load command!
```

When using `arm64-to-sim` on the device arm64 framework:
```
Swift/ErrorType.swift:200: Fatal error: Error raised at top level: Arm64ToSim.LcBuildVersionCommandAlreadyExistError()
```

**Comment by markst** [comment]
```
lipo -i ./Frameowork          
Architectures in the fat file: /Framework are: x86_64 arm64 
```

**Comment by darrarski** [comment]
Thanks for reporting! The `make-xcframework` works as intended. It uses [arm64-to-sim](https://github.com/darrarski/arm64-to-sim) library, which fails in your case. It's very hacky and experimental, but you can open an issue in the [arm64-to-sim](https://github.com/darrarski/arm64-to-sim) repository, describing the problem and including the framework you're trying to patch.
